### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by bzy-debug**

### CODE REVIEW

**Review by liweijian — APPROVED** [review]

**Comment by bzy-debug** [comment]
We add `init` function to this code snippet to make it complete. so that one can play with it at our [website](https://www.moonbitlang.com/docs/syntax/) without errors

**Comment by duselguy** [comment]
@bzy-debug 
1) To play with this code the user will have to add `bar` function definition.
2) The text above (to which the code relates) is explained in the code of `foo` function. To play with the code you added `init` function that calls `foo` function. What is the sense of the call of `bar` function in `init` function? What additional information adds the call of `bar` function to explain the text above?

**Comment by bzy-debug** [comment]
`bar` is used to demonstrate that **only** the last clause should be an expression, and what error will the compiler shows if there is an expression other than the last clause.

To run this snippet, user must comment out the third line of `bar`.

```
func bar() -> Int {
  let x = 1
  x + 1 // fail       <- this line should be commented out to run this snippet
  x + 2
}
```

**Comment by duselguy** [comment]
@bzy-debug 
That is the code:
image

Where is `bar` function?

**Comment by bzy-debug** [comment]
😳 Sorry for the mistake, will fix it tomorrow.

**Comment by duselguy** [comment]
@bzy-debug 
Also, these changes look (for now) incorrect:
image
Previous code explains that `init` function can't use expressions (i.e. should return `unit` type value). Although at this point the reader should understand the difference between statement and expression, and what is `unit` type.
New code will have the same behavior if replace `init` to `foo` (i.e. does not explain specific of `init` function). I will check it when workable moonbit distro will be available.

**Comment by duselguy** [comment]
@bzy-debug 
Ok, compiler error messages are the same for previous and new code. The only (?) `init` related message (_Init function must have no arguments and no return value_) exists for constructions like init->Int ...

**Comment by bzy-debug** [comment]
which code causes the error?

**Comment by duselguy** [comment]
@bzy-debug 
Compiler error messages are the same for previous and new (`// x // fail => x // fail`) code. It is OK.

**Comment by duselguy** [comment]
@bzy-debug 
Sorry, I'll have to revisit the code changes above: although the compiler produces the same error message for the previous and new code, the reasons are different:
1. Previous code: the compiler produces the error message because `init` function should return Unit type.
2. New code: the compiler produces the error message because of the excess expression (statement follows expression).

The reason of the error in the new code has nothing to `init` function.

**Pull request merged**
