### PR TITLE
bugfix of segment tree2 in index.md 

### PR DESCRIPTION
**Pull request by smallbearrr**
fixed bug of segment tree2 ’modify‘ function in docs example

### CODE REVIEW

**Comment by smallbearrr** [comment]
The original 'modify' fucntion will update more when there only have a part of need to modify (not the whole fragment). so i fixed it

**Comment by peter-jerry-ye** [comment]
@Lampese

**Comment by peter-jerry-ye** [comment]
Would you mind add a test here to show the bug first : https://github.com/moonbitlang/moonbit-docs/blob/main/next/sources/segment-tree/src/part2/top.mbt

**Comment by smallbearrr** [comment]
it looks like there have some error with to_json() method in top.mbt for (Data, Lazytag, Node), it is correct? @peter-jerry-ye

**Comment by peter-jerry-ye** [comment]
What do you mean by `errror`?

**Comment by smallbearrr** [comment]
> What do you mean by 'error'?
it display Data, Node have no method 'to_json()', but its already decleared in original code

**Comment by peter-jerry-ye** [comment]
The code compiles and test passes. All three data structures implement `ToJson` explicitly.

**Comment by peter-jerry-ye** [comment]
Test case:
```moonbit
let count : Ref[Int] = { val : 0 }

fn apply(self : Node, v : LazyTag) -> Node {
  count.val += 1
  match (self, v) {
    (Node(data=Data(sum=a, len=length), tag~, left~, right~), Tag(v) as new_tag) =>
      Node(
        data=Data(sum=a + v * length, len=length),
        tag=tag + new_tag,
        left~,
        right~,
      )
    (_, Nil) => self
    (Nil, _) => Nil
  }
}
test {
  let tree = build([1, 2, 3, 4, 5][:])
  inspect!(count.val, content="4") // after the PR will be 3
}
```

**Review by peter-jerry-ye — APPROVED** [review]
LGTM, thank you

**Pull request merged**
