### PR TITLE
Readme of AVL Tree 

### PR DESCRIPTION
**Pull request by ayan-joshi**
I have improved the readme file of AVL tree example , Now it explain the moonbit use in the AVL tree properly and also explains about AVL tree.
Mentioned in the issue #91 

Have a look at the pr @liweijian

### CODE REVIEW

**Comment by ayan-joshi** [comment]
@bobzhang

**Comment by ayan-joshi** [comment]
@bobzhang have a look at the pr

**Comment by ayan-joshi** [comment]
The pr was created aftee you assigned me the issue please have a look and merge my pr @bobzhang

**Comment by SaltyKitkat** [comment]
Seems great!
May I know why it's closed? @ayan-joshi

**Comment by bobzhang** [comment]
It looks like generated by AI

**Pull request closed without merging**
