### PR TITLE
feat: add code check

### PR DESCRIPTION
**Pull request by peter-jerry-ye**

### CODE REVIEW

**Review by bobzhang — COMMENTED** [review]
I made a syntax error but did not find error reported, did I miss anything

**Comment by peter-jerry-ye** [comment]
@bobzhang you need to write explicitly like:
``````markdown
```{code-block} moonbit
:class: top-level
```
``````
or
``````markdown
```{code-block} moonbit
:class: expr
```
``````
otherwise I can't distinguish with the already checked code.

**Comment by bobzhang** [comment]
Screenshot 2024-12-20 at 21 20 14

can you double check? it does not work for me, no error message found

**Comment by peter-jerry-ye** [comment]
Should be fixed now.

**Pull request merged**
